alertmanager:
  enabled: false

pushgateway:
  enabled: false

kube-state-metrics:
  enabled: false

nodeExporter:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi

server:
  resources:
    limits:
      cpu: 250m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 200Mi
  persistentVolume:
    enabled: false  # disable to avoid EBS usage
  retention: "24h"  # short retention to save space

  extraArgs:
    storage.ts

