replicaCount: 1

adminUser: admin
adminPassword: admin123

service:
  type: LoadBalancer
  port: 80

persistence:
  enabled: false

# Inline data sources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.observability.svc.cluster.local
        isDefault: true
        editable: true

      - name: Loki
        type: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local:3100
        editable: true

      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.observability.svc.cluster.local:3100
        editable: true

# Prebuilt dashboards from Grafana.com
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    node-exporter:
      gnetId: 1860
      revision: 29
      datasource: Prometheus
    kubernetes-pods:
      gnetId: 15757
      revision: 7
      datasource: Prometheus
    loki-logs:
      gnetId: 13639
      revision: 3
      datasource: Loki

